name: Deploy to Droplet

on:
  pull_request:
    types: [closed]
    branches:
      - main
    if: github.event.pull_request.merged == true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ 178.128.108.42 }}
          username: ${{ root }}
          key: ${{ ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC1SYp2jNGTCfNv+ZdWeR+8V9lj1ZagLrw9yR8cnECjB github-actions-deploy }}
          script: |
            # Navigate to your application directory
            cd C:\workspace\parkmate-be # Replace with your application's path

            # Pull the latest code from the main branch
            git pull origin main

            # Add any other commands to build, install, or restart your application
            # For example:
            # npm install
            # npm run build
            # sudo systemctl restart your_service_name