name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.DROPLET_IP }}

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set up environment variables
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export NODE_ENV=production
            
            # Clone or update repository
            if [ ! -d "/root/app" ]; then
              git clone https://github.com/${{ github.repository }}.git /root/app
            fi
            
            cd /root/app
            git pull origin main
            
            # Set up environment file
            echo "DB_HOST=localhost" > .env
            echo "DB_USER=appuser" >> .env
            echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            echo "DB_NAME=appdb" >> .env
            echo "NODE_ENV=production" >> .env
            echo "PORT=3000" >> .env
            
            # Install dependencies
            npm install --production
            
            # Set up MySQL
            sudo apt update
            sudo apt install mysql-server -y
            
            # Configure MySQL
            sudo mysql -e "CREATE DATABASE IF NOT EXISTS appdb;"
            sudo mysql -e "CREATE USER IF NOT EXISTS 'appuser'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
            sudo mysql -e "GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'localhost';"
            sudo mysql -e "FLUSH PRIVILEGES;"
            
            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            # Start or restart application
            pm2 delete all || true
            pm2 start npm --name "app" -- start
            pm2 save
            pm2 startup